object_names:
  - _background_
  - _tote_
  - band_aid_tape
  - bath_sponge
  - burts_bees_baby_wipes
  - colgate_toothbrush_4pk
  - crayons
  - duct_tape
  - expo_eraser
  - hanes_socks
  - laugh_out_loud_jokes
  - tissue_box
